name: Build and Push Docker Image

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  test-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run NestJS tests
        run: npm test --passWithNoTests

  build-and-push:
    needs: [test-app]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build Docker image
        run: docker build -t operator_service:2 .

      - name: Tag Docker image
        run: docker tag operator_service:2 $DOCKER_USERNAME/operator_service:2

      - name: Push Docker image to Docker Hub
        run: docker push $DOCKER_USERNAME/operator_service:2
